theme: jekyll

title: Angely C. Suarez DeJesus - Academic Portfolio
---

<img align="left" src="https://github.com/user-attachments/assets/2f85a604-914d-416e-82b7-b02d8bdc7f25" width="200" height="200" style="float left"/>

# Angely C. Suarez DeJesus
## PhD Student- Text & Technology Program, University of Central Florida

### About Me
<p>My name is Angely Suarez DeJesus and I am currently pursuing a PhD in the Text & Technology doctoral program at  the University of Central Florida. My interests are within the areas of rhetoric and composition. It entails the exploration of the ways in which AI algorithms managed by content moderators in large language models affect Latino women and other BIPOC groups  through textual rhetoric.

Other areas of interest are in the field of technical professional communication, digital media, and digital humanities.</p>

### Research Interests
- Topic 1
- Topic 2
- Topic 3

### Publications and/or Conferences

1. Paper Title, Journal, Year
2. Another Paper Title, Conference, Year

### Contact

- Email: your-email@example.com
- Office: Your office location

### Follow Me

- [Bluesky](https://bsky.app/your_bluesky_handle)
- [LinkedIn](https://linkedin.com/in/your_linkedin_profile)
- [GitHub](https://github.com/your_github_username)
